version: '3.8'

# Production overrides for LabFace
services:
  backend:
    restart: unless-stopped
    environment:
      NODE_ENV: production
      LOG_LEVEL: warn
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    restart: unless-stopped
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ml-service:
    restart: unless-stopped
    environment:
      ENVIRONMENT: production
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  mariadb:
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backups:/backups
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  minio:
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Add reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: labface-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
