version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: labface-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_DATABASE: ${DB_NAME:-labface}
      MYSQL_USER: ${DB_USER:-root}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - labface-network

  minio:
    image: minio/minio:latest
    container_name: labface-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - labface-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labface-backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-4000}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_NAME: ${DB_NAME:-labface}
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      JWT_SECRET: ${JWT_SECRET:-change_me}
      LATE_THRESHOLD_MINUTES: ${LATE_THRESHOLD_MINUTES:-30}
      ABSENT_AFTER_MINUTES: ${ABSENT_AFTER_MINUTES:-30}
    ports:
      - "4000:4000"
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - labface-network

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: labface-ml
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_NAME: ${DB_NAME:-labface}
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      ML_MODEL_PATH: /app/models
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./ml-service:/app
      - ml_models:/app/models
    networks:
      - labface-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labface-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_WS_URL: http://localhost:4000
      NEXT_PUBLIC_MINIO_URL: http://localhost:9000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - labface-network

  adminer:
    image: adminer:latest
    container_name: labface-adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - labface-network

volumes:
  mariadb_data:
  minio_data:
  ml_models:

networks:
  labface-network:
    driver: bridge
