version: '3.8'

# Development overrides
services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
    command: npm run dev

  ml-service:
    volumes:
      - ./ml-service:/app
      - ml_models:/app/models
    environment:
      ENVIRONMENT: development
